Output vhs.gif
Require quiczk
Set Shell zsh
Set FontSize 20
Set Width 1200
Set Height 750
Set TypingSpeed 55ms
Set Framerate 60
Set Padding 10

Hide
Type "clear"
Enter
Sleep 400ms
Show

Type@70ms "quiczk "
Sleep 250ms
Type@45ms "example.toml"
Sleep 650ms
Enter
Wait+Screen /reveal options/
Sleep 950ms
Enter
Wait+Screen /Linus Benedict Torvalds/
Sleep 750ms
Down@150ms
Sleep 350ms
Enter
Wait+Screen /next question/
Sleep 1300ms
Enter
Wait+Screen /reveal options/
Sleep 950ms
Enter
Wait+Screen /buy a new laptop/
Sleep 900ms
Down@150ms
Sleep 650ms
Enter
Wait+Screen /Explanation:/
Sleep 1600ms
Wait+Screen /Score:/
Sleep 2800ms
Type "q"
Sleep 400ms
