Output vhs.gif
Require quiczk
Set Shell zsh
Set FontSize 20
Set Width 1200
Set Height 750
Set TypingSpeed 75ms
Set Framerate 60
Set Padding 10

Hide
Type "clear"
Enter
Sleep 500ms
Show

Type@150ms "quiczk"
Sleep 500ms
Type " e"
Sleep 500ms
Tab
Sleep 500ms
Enter
Wait+Screen /reveal options/
Sleep 1500ms
Enter
Wait+Screen /Peerawat Monviset/
Sleep 2s
Down
Sleep 800ms
Enter
Wait+Screen /next question/
Sleep 2s
Enter
Wait+Screen /reveal options/
Sleep 1200ms
Enter
Wait+Screen /How do you exit Vim/
Sleep 2s
Enter
Wait+Screen /Score:/
Sleep 3500ms
Type "q"
Sleep 1s
